# This file was generated by GoReleaser. DO NOT EDIT.
cask "motifini" do
  version "0.3.1"

  on_macos do
    sha256 "0754647906aa88d9baa172be99f4714e32ee5669932aac5951f96147dae98bb7"
    url "https://github.com/davidnewhall/motifini/releases/download/v#{version}/motifini_#{version}_darwin_all.tar.gz",
        verified: "github.com/davidnewhall/motifini"
  end

  on_linux do
    on_intel do
      sha256 "aeec38461e7a083c6505296bace7ded99211e7ab71464c86a9f59c6de8a14a9a"
      url "https://github.com/davidnewhall/motifini/releases/download/v#{version}/motifini_#{version}_linux_amd64.tar.gz",
        verified: "github.com/davidnewhall/motifini"
    end
    on_arm do
      sha256 "e50397d53df0292d9d1b260e169f6e4c2108e15337baf45cf547c52149efbbcd"
      url "https://github.com/davidnewhall/motifini/releases/download/v#{version}/motifini_#{version}_linux_arm64.tar.gz",
        verified: "github.com/davidnewhall/motifini"
    end
  end

  name "motifini"
  desc "SecuritySpy Telegram Bot - motion clips and camera alerts in Telegram"
  homepage "https://github.com/davidnewhall/motifini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "motifini"

  postflight do
    conf_dir = HOMEBREW_PREFIX/"etc"
    conf_dir.mkpath
    FileUtils.cp "#{staged_path}/examples/motifini.conf.example", conf_dir/"motifini.conf.example"
    FileUtils.cp "#{staged_path}/examples/motifini.conf.example", conf_dir/"motifini.conf" unless (conf_dir/"motifini.conf").exist?
    (HOMEBREW_PREFIX/"var/log").mkpath
    label = "io.golift.motifini"
    agent = Pathname.new(Dir.home)/"Library/LaunchAgents/#{label}.plist"
    agent.dirname.mkpath
    binary = HOMEBREW_PREFIX/"bin/motifini"
    conf = conf_dir/"motifini.conf"
    log = HOMEBREW_PREFIX/"var/log/motifini.log"
    agent.write <<~XML
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key><string>#{label}</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{binary}</string>
          <string>--config</string>
          <string>#{conf}</string>
        </array>
        <key>RunAtLoad</key><true/>
        <key>KeepAlive</key><true/>
        <key>WorkingDirectory</key><string>#{HOMEBREW_PREFIX}</string>
        <key>StandardOutPath</key><string>#{log}</string>
        <key>StandardErrorPath</key><string>#{log}</string>
      </dict>
      </plist>
    XML
  end

  uninstall_postflight do
    label = "io.golift.motifini"
    agent = Pathname.new(Dir.home)/"Library/LaunchAgents/#{label}.plist"
    system "/bin/launchctl", "bootout", "gui/#{Process.uid}/#{label}"
    agent.delete if agent.exist?
  end

  # No zap stanza required

  caveats <<~EOS
    Edit #{HOMEBREW_PREFIX}/etc/motifini.conf then:
      launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/io.golift.motifini.plist
    Restart: launchctl kickstart -k gui/$(id -u)/io.golift.motifini
    Stop:    launchctl bootout gui/$(id -u)/io.golift.motifini
    (brew services does not manage casks.)
  EOS
end
