# This file was generated by GoReleaser. DO NOT EDIT.
cask "unpoller" do
  version "5.1.0"

  on_macos do
    on_arm do
      sha256 "67d518cc8c54708e9fecfad8bafc1db0059bcf2d8ded3c4a4b2437c86a78157d"
      url "https://github.com/unpoller/unpoller/releases/download/v#{version}/unpoller_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "30afadb2cc2f97849014ddd9750018e2f23e8cc07ac775287992da268656b0c9"
      url "https://github.com/unpoller/unpoller/releases/download/v#{version}/unpoller_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "unpoller"
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unpoller"

  service "run ["#{opt_bin}/unpoller", "--config", "#{etc}/unpoller/up.conf"]
keep_alive true
log_path "#{var}/log/unpoller.log"
error_log_path "#{var}/log/unpoller.log"
"

  postflight do
    (etc/"unpoller").mkpath
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf.example"
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf" unless File.exist?("#{etc}/unpoller/up.conf")
  end

  # No zap stanza required

  caveats <<~EOS
    Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
  EOS
end
