# This file was generated by GoReleaser. DO NOT EDIT.
cask "unpoller" do
  version "5.2.4"

  on_macos do
    sha256 "a56b0f66328e3348e068dcd1c6f0cf069dd978582e56507003e5c9f91e12a391"
    url "https://github.com/unpoller/unpoller/releases/download/v#{version}/unpoller_#{version}_darwin_all.tar.gz"
  end

  name "unpoller"
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unpoller"

  service "run ["#{opt_bin}/unpoller", "--config", "#{etc}/unpoller/up.conf"]
keep_alive true
log_path "#{var}/log/unpoller.log"
error_log_path "#{var}/log/unpoller.log"
"

  postflight do
    (etc/"unpoller").mkpath
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf.example"
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf" unless File.exist?("#{etc}/unpoller/up.conf")
  end

  # No zap stanza required

  caveats <<~EOS
    Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
  EOS
end
