# This file was generated by GoReleaser. DO NOT EDIT.
cask "unpoller" do
  version "3.5.0"

  on_macos do
    on_intel do
      sha256 "cdfc9a38262783586536f2681d698e22e88d080a64ef6ed4f600b60497accf80"
      url "https://github.com/unpoller/unpoller/releases/download/v#{version}/unpoller_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60dd3c7ea6b09361024a99ae53dce4ed36d1b871bda60b477770a9a3e8772ff4"
      url "https://github.com/unpoller/unpoller/releases/download/v#{version}/unpoller_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "unpoller"
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unpoller"

  service "run ["#{opt_bin}/unpoller", "--config", "#{etc}/unpoller/up.conf"]
keep_alive true
log_path "#{var}/log/unpoller.log"
error_log_path "#{var}/log/unpoller.log"
"

  postflight do
    (etc/"unpoller").mkpath
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf.example"
    FileUtils.cp "#{staged_path}/examples/up.conf.example", "#{etc}/unpoller/up.conf" unless File.exist?("#{etc}/unpoller/up.conf")
  end

  # No zap stanza required

  caveats <<~EOS
    Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
  EOS
end
