# This file was generated by GoReleaser. DO NOT EDIT.
cask "xt" do
  version "0.3.0"

  on_macos do
    sha256 "12fea6881164982ff5c7e2bef0c7b3b7d2582c767d902c3f025c732ac8663d98"
    url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "b4b11d144235c6d966e97043f5828faa0f5aafc616f6886ba739a3fe2a181c9e"
      url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7420e269d13986f6b3564829422a0bbdb2a79d8046db120f5bda0931551898d3"
      url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xt"
  desc "eXtractor Tool - Recursively decompress archives"
  homepage "https://unpackerr.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xt"

  # No zap stanza required
end
