# This file was generated by GoReleaser. DO NOT EDIT.
cask "xt" do
  version "0.2.2"

  on_macos do
    sha256 "250f93deb06f046f775e330d30762b07bc8a1ce3f37752e081561eae0a1acfa4"
    url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_darwin_all.tar.gz",
        verified: "github.com/Unpackerr/xt"
  end
  on_linux do
    on_arm do
      sha256 "8938c5a35aa9ccb1879602f2a611a609f2e831d457d66dc40a34873a776a1317"
      url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Unpackerr/xt"
    end
    on_intel do
      sha256 "6af7158fa7011633871bdfb423218476c51d2905f4ba386728826c07e1eb37ff"
      url "https://github.com/Unpackerr/xt/releases/download/v#{version}/xt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Unpackerr/xt"
    end
  end

  name "xt"
  desc "eXtractor Tool - Recursively decompress archives"
  homepage "https://unpackerr.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xt"

  # No zap stanza required
end
