# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpoller < Formula
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"
  version "2.23.0"
  license "MIT"

  on_macos do
    url "https://github.com/unpoller/unpoller/releases/download/v2.23.0/unpoller_2.23.0_darwin_all.tar.gz"
    sha256 "ac0947665888eaaecfc7508bc7252527b9ae0afdb961ffb6460bb9bf02e2f509"

    def install
      bin.install "unpoller"
      etc.mkdir "unpoller"
      etc.install "examples/up.conf" => "unpoller/up.conf.example"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.23.0/unpoller_2.23.0_linux_amd64.tar.gz"
      sha256 "e855365e7342bc596a854e383a95e88f02ba40f477de003505b785a7b0bb60a8"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.23.0/unpoller_2.23.0_linux_armv6.tar.gz"
      sha256 "4410a6a3f12e45ce63c4d2467a64ba1589b9ffa148ac35fa89eecdb72623fb3b"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.23.0/unpoller_2.23.0_linux_arm64.tar.gz"
      sha256 "05336cb258321cad6e623280e72ffae86393117f118e095bab91fd46322bfc23"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
  end

  conflicts_with "unifi-poller"

  def post_install
    etc.install "examples/up.conf" => "unpoller/up.conf"
  end

  def caveats
    <<~EOS
      Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
    EOS
  end

  service do
    run ["#{opt_bin}/unpoller", "--config", "#{etc}/unpoller/up.conf"]
    keep_alive true
    log_path "#{var}/log/unpoller.log"
    error_log_path "#{var}/log/unpoller.log"
  end

  test do
    assert_match "unpoller v#{version}", shell_output("#{bin}/unpoller -v 2>&1", 2)
  end
end
