# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpoller < Formula
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"
  version "2.17.0"
  license "MIT"

  on_macos do
    url "https://github.com/unpoller/unpoller/releases/download/v2.17.0/unpoller_2.17.0_darwin_all.tar.gz"
    sha256 "e80b04e9d8e3ded5e6b80c524a45969bd50cb3e98b70ca6d6f97c09236802fea"

    def install
      bin.install "unpoller"
      etc.mkdir "unpoller"
      etc.install "examples/up.conf" => "unpoller/up.conf.example"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.17.0/unpoller_2.17.0_linux_amd64.tar.gz"
      sha256 "a18c50b8dc66a9334442b243862c60c244474f4dbe0ac7695a7d4496b9937e63"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.17.0/unpoller_2.17.0_linux_armv6.tar.gz"
      sha256 "88c9ef44f1ac8fdce351aaba96fbf762be60b4426af0a33e7a47e21f16106a39"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.17.0/unpoller_2.17.0_linux_arm64.tar.gz"
      sha256 "7e30a5b16da16872e02c2bea70996e77104c85d0775b0ca4c3208cd8faa54251"
      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
  end

  conflicts_with "unifi-poller"

  def post_install
    etc.install "examples/up.conf" => "unpoller/up.conf"
  end

  def caveats
    <<~EOS
      Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
    EOS
  end

  service do
    run ["#{opt_bin}/unpoller", "--config", "#{etc}/unpoller/up.conf"]
    keep_alive true
    log_path "#{var}/log/unpoller.log"
    error_log_path "#{var}/log/unpoller.log"
  end

  test do
    assert_match "unpoller v#{version}", shell_output("#{bin}/unpoller -v 2>&1", 2)
  end
end
