# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpoller < Formula
  desc "Polls a UniFi controller, exports metrics to InfluxDB, Prometheus and Datadog"
  homepage "https://unpoller.com/"
  version "2.8.1"
  license "MIT"

  on_macos do
    url "https://github.com/unpoller/unpoller/releases/download/v2.8.1/unpoller_2.8.1_darwin_all.tar.gz"
    sha256 "b2e3f676ce56c46b13b5acfd3ae7c5001c98c6c9c1abcdb2192c7c65328bc812"

    def install
      bin.install "unpoller"
      etc.mkdir "unpoller"
      etc.install "examples/up.conf" => "unpoller/up.conf.example"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/unpoller/unpoller/releases/download/v2.8.1/unpoller_2.8.1_linux_amd64.tar.gz"
      sha256 "c3bed5a107a5057b184e402de85525fa5e1d4a456a0cb562b9879fff5e5f9b3e"

      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.8.1/unpoller_2.8.1_linux_arm64.tar.gz"
      sha256 "f2602b18b760c2baa2b535ae9220efa223b0a95ff76e6fa513d6da6b23d38486"

      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/unpoller/unpoller/releases/download/v2.8.1/unpoller_2.8.1_linux_armv6.tar.gz"
      sha256 "daedd65e0e8bdb9cc2fb4ed767cff240ba14621e2330ab9a40fbdd0317d39f64"

      def install
        bin.install "unpoller"
        etc.mkdir "unpoller"
        etc.install "examples/up.conf" => "unpoller/up.conf.example"
      end
    end
  end

  conflicts_with "unifi-poller"

  def post_install
    etc.install "examples/up.conf" => "unpoller/up.conf"
  end

  def caveats
    <<~EOS
      Edit the config file at #{etc}/unpoller/up.conf then start unpoller with brew services start unpoller ~ log file: #{var}/log/unpoller.log The manual explains the config file options: man unpoller
    EOS
  end

  service do
    run [opt_bin/"unpoller", "--config", etc/"unpoller/up.conf"]
    keep_alive true
    log_path var/"log/unpoller.log"
    error_log_path var/"log/unpoller.log"
  end

  test do
    assert_match "unpoller v#{version}", shell_output("#{bin}/unpoller -v 2>&1", 2)
  end
end
