# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xt < Formula
  desc "eXtractor Tool - Recursively decompress archives"
  homepage "https://unpackerr.com/"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/Unpackerr/xt/archive/refs/tags/v0.2.0.tar.gz"
    sha256 "d30a3f403a93921053dbb8ba99f2c6a7e2c0653871e3b2f45ff0425fd5b1be27"

    def install
      bin.install "xt"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Unpackerr/xt/releases/download/v0.1.1/xt_0.1.1_linux_amd64.tar.gz"
        sha256 "06113a42ef5be37e0d1a61ddeda3450dd906cf120df23cf4b77673e38cb19ff9"

        def install
          bin.install "xt"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Unpackerr/xt/releases/download/v0.1.1/xt_0.1.1_linux_armv6.tar.gz"
        sha256 "1111fc33ff335de65edf0b55442a20817aabcad1d27f99522129516a88caadbe"

        def install
          bin.install "xt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Unpackerr/xt/releases/download/v0.1.1/xt_0.1.1_linux_arm64.tar.gz"
        sha256 "c25e6a678fdcf55fc69e74786bf11e54579fd97e767715c9263389c429218090"

        def install
          bin.install "xt"
        end
      end
    end
  end

  test do
    assert_match "xt v#{version}", shell_output("#{bin}/xt -v 2>&1", 2)
  end
end
