# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xt < Formula
  desc "eXtractor Tool - Recursively decompress archives"
  homepage "https://unpackerr.com/"
  version "0.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/Unpackerr/xt/releases/download/v0.0.2/xt_0.0.2_darwin_all.tar.gz"
    sha256 "b395ac53715c42bde0311c8a71b95c1bf3f414270bc0bab4f47cb5b40d25c2bf"

    def install
      bin.install "xt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Unpackerr/xt/releases/download/v0.0.2/xt_0.0.2_linux_armv6.tar.gz"
      sha256 "aab7e5bb3e88c1506996e2b6ffc9823c0a66e77125b1455f79bdc243727a19bb"

      def install
        bin.install "xt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Unpackerr/xt/releases/download/v0.0.2/xt_0.0.2_linux_arm64.tar.gz"
      sha256 "1bbddb6133b0e471d3b4d9482309e4ca9d6bf97d74e43a179d66f7938a9681ef"

      def install
        bin.install "xt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Unpackerr/xt/releases/download/v0.0.2/xt_0.0.2_linux_amd64.tar.gz"
      sha256 "4a986040cfaa97e5fb0b9be46c3fa444e2a84d0d66166b509c516b908ca81eb8"

      def install
        bin.install "xt"
      end
    end
  end

  test do
    assert_match "xt v#{version}", shell_output("#{bin}/xt -v 2>&1", 2)
  end
end
