# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xt < Formula
  desc "eXtractor Tool - Recursively decompress archives"
  homepage "https://unpackerr.com/"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/Unpackerr/xt/releases/download/v0.2.0/xt_0.2.0_darwin_all.tar.gz"
    sha256 "5988fb21159fc983e23802cef9ed85a592d951b8d4786643bc302b4aceb03d4b"

    define_method(:install) do
      bin.install "xt"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Unpackerr/xt/releases/download/v0.2.0/xt_0.2.0_linux_amd64.tar.gz"
      sha256 "f6ab9cb465f6f9a35647b428c2b48ab6c4a513017688e45c12c0727fb7c8bce1"
      define_method(:install) do
        bin.install "xt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Unpackerr/xt/releases/download/v0.2.0/xt_0.2.0_linux_armv6.tar.gz"
      sha256 "d8883d6bbe629937d693926002443401912a1e0b05d140cb2f0a390d93e5e45a"
      define_method(:install) do
        bin.install "xt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Unpackerr/xt/releases/download/v0.2.0/xt_0.2.0_linux_arm64.tar.gz"
      sha256 "90836b7f010a24934a969d65f63bc994d30d265de6a25914b6127106e67d3a0b"
      define_method(:install) do
        bin.install "xt"
      end
    end
  end

  test do
    assert_match "xt v#{version}", shell_output("#{bin}/xt -v 2>&1", 0)
  end
end
